### ISSUE TITLE
Can't come today

### ISSUE THREAD

**Issue by eikooc** [e-conomic/client-side-application-course#24]
Do you record the presentations? Or is it just bad luck?
I will come next week. What will I miss?

**Comment by hulvei3** [comment]
can you please give me your email adress

**Comment by eikooc** [comment]
jamieneubert@gmail.com

**Comment by eikooc** [comment]
jamie.neubert@gmail.com

**Comment by DenLilleMand** [comment]
Min cykel brød sammen på Nørrebro, da klokken var 11.40, så jeg når det heller ikke. Jeg er der også først næste gang. Jeg har OK styr på react så niveau mæssigt er det ikke et problem. Min mail er mattinielsen5@hotmail

**Comment by hulvei3** [comment]
@DenLilleMand  har skrevet på Slack
