### ISSUE TITLE
istanbul to process more that one test.js file

### ISSUE THREAD

**Issue by ghost** [e-conomic/client-side-application-course#96]
When creating the unit tests for the code, I put the tests into multiple .js files as I did not want to create one huge test file for all the classes.

But how do I make istanbul to process a set of files in a directory instead of just the single file being passed as parameter?

**Comment by ghost** [comment]
This is the error, I get. Tried to switch to babel-istanbul with no success.

$ npm run coverage

> MyApp@0.0.1 coverage C:\git\e-conomic\client-side-application-course\BennyTordrupVisma\Application
> babel-istanbul cover node_modules/.bin/_mocha

No coverage information was collected, exit without writing coverage information
C:\git\e-conomic\client-side-application-course\BennyTordrupVisma\Application\node_modules.bin_mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js](C:Gite-conomicclient-side-application-courseBennyTordrupVismaApplicationnode_modulesbabel-istanbullibhook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at runFn (C:\Git\e-conomic\client-side-application-course\BennyTordrupVisma\Application\node_modules\babel-istanbul\lib\command\common\run-with-cover.js:125:16)
    at C:\Git\e-conomic\client-side-application-course\BennyTordrupVisma\Application\node_modules\babel-istanbul\lib\command\common\run-with-cover.js:258:17
    at C:\Git\e-conomic\client-side-application-course\BennyTordrupVisma\Application\node_modules\babel-istanbul\lib\util\file-matcher.js:68:16

**Comment by ghost** [comment]
Finally got it working.

Using istanbul package 1.0.0-alpha.2

Command:      "coverage": "istanbul cover node_modules/mocha/bin/_mocha",

**Comment by hulvei3** [comment]
Great!! I wonder if I tried with another alpha release. Thanks for letting us know!

**Comment by memphis88** [comment]
Likewise, it worked for me with that specific alpha version and not the default (0.4.2).

**Comment by hulvei3** [comment]
cool - remember to require all your src files when running istanbul. Otherwise it gives you a better coverage than you actually have :)
