### ISSUE TITLE
SOAP client?

### ISSUE THREAD

**Issue by ghost** [e-conomic/client-side-application-course#99]
Hi

Does any of you know of a good SOAP client for calling Windows Communication Foundation services from Javascript?

**Comment by hulvei3** [comment]
there seems to be several out there when you search for it.
- https://www.npmjs.com/package/soap
- https://www.npmjs.com/package/node-soap
- https://www.npmjs.com/package/easysoap

Haven't tried any of them though

**Comment by ghost** [comment]
It was more a question if anybody had experience with a SOAP client...

Tried the first one - npm install gives the following error:

C:\git\e-conomic\client-side-application-course\BennyTordrupVisma\FinalProject\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\e-conomic\client-side-application-course\BennyTordrupVisma\FinalProject\node_modules\ursa
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
MyApp@0.0.1 C:\git\e-conomic\client-side-application-course\BennyTordrupVisma\FinalProject
`-- (empty)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN MyApp@0.0.1 No description
npm WARN MyApp@0.0.1 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.3.1
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE

npm ERR! ursa@0.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ursa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\git\e-conomic\client-side-application-course\BennyTordrupVisma\FinalProject\npm-debug.log
npm ERR! code 1

**Comment by memphis88** [comment]
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Tried resolving this? I guess npm cannot install python on its own so you have to take care of installing it and setting the PATH variable on Windows

https://github.com/nodejs/node-gyp#installation some insight on what you might be missing
